SELECT 
NR_MOVIMENTO_ESTOQUE,
CD_LOCAL_ESTOQUE,
OBTER_DESC_LOCAL_ESTOQUE(CD_LOCAL_ESTOQUE)DS_ESTOQUE,
DT_MOVIMENTO_ESTOQUE,
CD_OPERACAO_ESTOQUE,
OBTER_DESC_OPERACAO_ESTOQUE(CD_OPERACAO_ESTOQUE)DS_OPERACAO,
CD_ACAO,
CD_MATERIAL,
OBTER_DESC_MATERIAL(CD_MATERIAL)DS_MATERIAL,
OBTER_DADOS_MATERIAL(CD_MATERIAL,'CGRU')CD_GRUPO_MATERIAL,
OBTER_DADOS_MATERIAL(CD_MATERIAL,'GRU')DS_GRUPO_MATERIAL,
OBTER_DADOS_MATERIAL(CD_MATERIAL,'CSUB')CD_SUBGRUPO_MATERIAL,
OBTER_DADOS_MATERIAL(CD_MATERIAL,'SUB')DS_SUBGRUPO_MATERIAL,
OBTER_DADOS_MATERIAL(CD_MATERIAL,'CCLA')CD_CLASSE_MATERIAL,
OBTER_DADOS_MATERIAL(CD_MATERIAL,'CLA')DS_CLASSE_MATERIAL,
DT_MESANO_REFERENCIA,
QT_MOVIMENTO,
CD_UNIDADE_MEDIDA_ESTOQUE,
CD_SETOR_ATENDIMENTO,
QT_ESTOQUE,
DT_PROCESSO,
CD_LOCAL_ESTOQUE_DESTINO,
OBTER_DESC_LOCAL_ESTOQUE(CD_LOCAL_ESTOQUE_DESTINO)DS_ESTOQUE_DESTINO,
CD_CENTRO_CUSTO,
OBTER_DESC_CENTRO_CUSTO(CD_CENTRO_CUSTO)DS_CENTRO_CUSTO
FROM MOVIMENTO_ESTOQUE
WHERE DT_PROCESSO BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)-1/86400
--AND CD_LOCAL_ESTOQUE IN (70,82,83,84,85,86,183,184,194)