SELECT 
NR_MOVIMENTO_ESTOQUE,
CD_LOCAL_ESTOQUE,
DT_MOVIMENTO_ESTOQUE,
CD_OPERACAO_ESTOQUE,
CD_ACAO,
CD_MATERIAL,
OBTER_DESC_MATERIAL(CD_MATERIAL)DS_MATERIAL,
DT_MESANO_REFERENCIA,
QT_MOVIMENTO,
CD_UNIDADE_MEDIDA_ESTOQUE,
CD_SETOR_ATENDIMENTO,
QT_ESTOQUE,
DT_PROCESSO,
CD_LOCAL_ESTOQUE_DESTINO,
CD_CENTRO_CUSTO
FROM MOVIMENTO_ESTOQUE
WHERE DT_PROCESSO BETWEEN TO_DATE('01/01/2026 00:00:00','DD/MM/YYYY HH24:MI:SS') AND TRUNC(SYSDATE)-1/86400
AND CD_LOCAL_ESTOQUE IN (70,82,83,84,85,86,183,184,194)