
PACIENTE_DIA = """
SELECT
    A.NR_SEQUENCIA,
    A.NR_ATENDIMENTO,
    A.CD_SETOR_ATENDIMENTO,
    A.QT_PACIENTE_DIA
FROM WEIS_OCUP_HOSP_P312 A
WHERE 2=2
AND TRUNC(A.DT_REFERENCIA) BETWEEN TO_DATE('01/01/2025 00:00:00','dd/mm/yyyy hh24:mi:ss') AND TRUNC(SYSDATE)-1/86400
"""

LOCAL_ESTOQUE = """
SELECT
    CD_LOCAL_ESTOQUE,
    DS_LOCAL_ESTOQUE
FROM LOCAL_ESTOQUE
WHERE 2=2
AND CD_LOCAL_ESTOQUE IN (70,82,83,84,85,86,183,184,194)
"""

MATERIAL = """
SELECT
    CD_MATERIAL,
    DS_MATERIAL,
    CD_UNIDADE_MEDIDA_ESTOQUE,
    OBTER_DADOS_MATERIAL(CD_MATERIAL,'GRU')DS_GRUPO_MATERIAL,
    OBTER_DADOS_MATERIAL(CD_MATERIAL,'SUB')DS_SUBGRUPO_MATERIAL
FROM MATERIAL
WHERE 2=2
AND IE_SITUACAO = 'A'
"""